# Generated by Django 5.1.4 on 2025-03-06 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='Product',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='Image',
        ),
        migrations.AddField(
            model_name='image',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.review'),
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(related_name='products', to='Product.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='Product.category'),
        ),
    ]
