# Generated by Django 5.1.4 on 2025-03-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='last4',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
