# Generated by Django 5.1.4 on 2025-03-10 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_orders_total_price_alter_cart_total_price'),
        ('User', '0002_remove_user_image_url_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promoCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.promocode'),
        ),
    ]
